springdoc:
  swagger-ui:
    path: /
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${db.port}/${db.dbname}
    username: ${db.username}
    password: ${db.password}

  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: "elastic" # 아이디 elastic
      password: "elastic"  #비밀번호 elastic

  config:
    import: "classpath:API-KEY.yml"

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy:
          org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


  logstash:
    image: logstash:8.15.3
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf # 이 부분이 맞는지는 다시 한번 확인 및 검증이 필요함
      - /usr/local/lib/mariadb-java-client.jar:/usr/share/logstash/mariadb-java-client.jar # 이 부분이 맞는지는 다시 한번 확인 및 검증이 필요함
    environment:
      - LS_JAVA_OPTS="-Xmx1g -Xms1g"
      - JDBC_USER=${db.username}
      - JDBC_PASSWORD=${db.password}
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
      - mariadb
    networks:
      - elastic-net

kakao:
  client_id:
    rest_api_key: ${kakao.client_id.rest_api_key}
  redirect_uri: ${kakao.redirect_uri}

token:
  secret: ${token.secret}
  access_token_expiration_time: ${token.access_token_expiration_time}
  refresh_token_expiration_time: ${token.refresh_token_expiration_time}

