springdoc:
  swagger-ui:
    path: /
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${db.port}/${db.dbname}
    username: ${db.username}
    password: ${db.password}

  config:
    import: "classpath:API-KEY.yml"

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy:
          org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
kakao:
  client_id:
    rest_api_key: ${kakao.client_id.rest_api_key}
  redirect_uri: ${kakao.redirect_uri}
