springdoc:
  swagger-ui:
    path: /
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${db.port}/${db.dbname}
    username: ${db.username}
    password: ${db.password}
  config:
    import: "classpath:API-KEY.yml"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
